---
apiVersion: v1
kind: Service
metadata:
    name: webapp-service
spec:
    selector:
        app: microlearning-webapp
    ports:
      - name: http
        protocol: TCP
        port: 80
        targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: webapp-ingress
spec:
  rules:
    - host: microlearning.workcale.io
      http:
        paths:
          - path: /
            backend:
              serviceName: webapp-service
              servicePort: 80
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: microlearning-webapp
    labels:
        app: microlearning-webapp
spec:
    replicas: 1
    selector:
      matchLabels:
        app: microlearning-webapp
    template:
      metadata:
          labels:
            app: microlearning-webapp
      spec:
        containers:
          - name: microlearning-webapp
            image: workcale/microlearning-webapp:debug
            ports:
              - containerPort: 80
