---
apiVersion: v1
kind: Service
metadata:
    name: springboot-vault-service
spec:
    selector:
        app: springboot-vault
    ports:
      - name: http
        protocol: TCP
        port: 8080
        targetPort: 8080
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: springboot-vault
    labels:
        app: springboot-vault
spec:
    replicas: 1
    selector:
      matchLabels:
        app: springboot-vault
    template:
      metadata:
          labels:
            app: springboot-vault
      spec:
        containers:
          - name: springboot-vault
            image: workcale/springboot-vault:approle
            ports:
              - containerPort: 8080
            envFrom:
              - secretRef:
                  name: springboot-vault-secret
