---
apiVersion: v1
kind: Service
metadata:
    name: api-service
spec:
    selector:
        app: microlearning-api
    ports:
      - name: http
        protocol: TCP
        port: 8080
        targetPort: 8080
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: api-ingress
spec:
  rules:
    - host: api.microlearning.workcale.io
      http:
        paths:
          - path: /
            backend:
              serviceName: api-service
              servicePort: 8080
            
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: microlearning-api
    labels:
        app: microlearning-api
spec:
    replicas: 1
    selector:
      matchLabels:
        app: microlearning-api
    template:
      metadata:
          labels:
            app: microlearning-api
      spec:
        containers:
          - name: microlearning-api
            image: workcale/microlearning-api:latest
            ports:
              - containerPort: 8080
            env:
              - name: "SPRING_PROFILES_ACTIVE"
                value: "docker"
