---
apiVersion: v1
kind: Service
metadata:
    name: wiki
spec:
    selector:
        app: wiki
    ports:
      - name: http
        protocol: TCP
        port: 8081
        targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: wiki
    labels:
        app: wiki
spec:
    replicas: 1
    selector:
      matchLabels:
        app: wiki
    template:
      metadata:
          labels:
            app: wiki
      spec:
        containers:
          - name: wiki
            image: workcale/microlearning-wiki:latest
            ports:
              - containerPort: 8081
