# docker-compose -f docker-compose.yaml up
version: "3.8"

services:
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - 8001:8001
  microlearning-api:
    image: workcale/microlearning-api:latest
    ports:
      - 8090:8080
    environment:
      SPRING_PROFILES_ACTIVE: docker
  wiki:
    image: workcale/microlearning-wiki:latest
    ports:
      - 8091:8081
  webapp:
    image: workcale/microlearning-webapp:docker
    ports:
      - 3000:80