{
 "title": "Microlearning requests dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "4XX requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=~\"/api/v1/microlearning/.*\",status=~\"4..\"}[5m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "5XX requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{uri=~\"/api/v1/microlearning/.*\",status=~\"5..\"}[5m])",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "2XX requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status=~\"2..\", uri=~\"/api/v1/microlearning/.*\"}[5m])",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}